language: python
python:
    - 2.7
    - 3.2
    - 3.3
    - 3.4
before_install:
    # add users/groups for wheel and portage
    - sudo useradd -g 10 wheel
    - sudo useradd -u 250 -g 250 portage

    # install-info is used by the info regen trigger
    - sudo apt-get update -qq
    - sudo apt-get install -y install-info

    # don't output the "this is not dpkg install-info anymore, but GNU install-info..." warning
    - sudo mv /usr/bin/ginstall-info /usr/bin/install-info
install:
    - git clone git://github.com/pkgcore/snakeoil.git "${VIRTUAL_ENV}"/snakeoil
    - pushd "${VIRTUAL_ENV}"/snakeoil
    - python setup.py install --install-headers "${VIRTUAL_ENV}"/include/snakeoil
    - popd
script:
    - python setup.py build_ext -I "${VIRTUAL_ENV}"/include
    - python setup.py test
