language: python
python:
    - 2.7
    - 3.3
    - 3.4
env: TOXENV=py${TRAVIS_PYTHON_VERSION/\./}
before_install:
    # add user/group for portage and wheel
    - sudo groupadd wheel
    - sudo groupadd -g 250 portage
    - sudo useradd -u 250 -g 250 portage

    # install-info is used by the info regen trigger
    - sudo apt-get install -y install-info

    # don't output the "this is not dpkg install-info anymore, but GNU install-info..." warning
    - sudo mv /usr/bin/ginstall-info /usr/bin/install-info
install: pip install tox coveralls
script: tox -e ${TOXENV}
after_success:
    # upload coverage data to coveralls.io
    - pushd .tox/${TOXENV}/lib/python*/site-packages
    - coveralls
    - popd
