language: python
python:
    - 2.7
    - 3.3
    - 3.4
before_install:
    # install-info is used by the info regen trigger
    - sudo apt-get install -y install-info
    # don't output the "this is not dpkg install-info anymore, but GNU install-info..." warning
    - sudo mv /usr/bin/ginstall-info /usr/bin/install-info
install: pip install 'tox<2' coveralls
script: tox -e py${TRAVIS_PYTHON_VERSION/\./}
after_success:
    # upload coverage data to coveralls.io
    - pushd .tox/py${TRAVIS_PYTHON_VERSION/\./}/lib/python*/site-packages
    - coveralls
    - popd
